export const DefaultThemeColor = {
    project_id: '123',
    color: {
        statusCode: 200,
        message: 'success',
        result: {
            _id: '63ca80e894461ae48cb57496',
            projectId: '63ca80e894461ae48cb57493',
            colors: {
                primary: {
                    pri100: '#DBE4F0',
                    pri200: '#95B8E4',
                    pri300Main: '#328DF6',
                    pri400: '#2B6DBA',
                    pri500: '#2C4B72',
                    pri600: '#233247',
                },
                secondary: {
                    sec100: '#DCEAEF',
                    sec200: '#88C2D4',
                    sec300Main: '#21A2BF',
                    sec400: '#2D768B',
                    sec500: '#2B4F59',
                    sec600: '#22353A',
                },
                systemColor1: {
                    sys100: '#FADCDA',
                    sys200: '#FD948C',
                    sys300Main: '#F94948',
                    sys400: '#C73733',
                    sys500: '#733430',
                    sys600: '#4D2725',
                },
                systemColor2: {
                    sys100: '#F9E8A4',
                    sys200: '#F6DA6B',
                    sys300Main: '#F0C20B',
                    sys400: '#D9A808',
                    sys500: '#A67503',
                    sys600: '#654506',
                },
                systemColor3: {
                    sys100: '#D9E6DC',
                    sys200: '#9AC3A4',
                    sys300Main: '#439D62',
                    sys400: '#198A48',
                    sys500: '#285837',
                    sys600: '#1F3625',
                },
                systemColor4: {
                    sys100: '#EEDEF1',
                    sys200: '#DC97E7',
                    sys300Main: '#DA38FA',
                    sys400: '#A52FBC',
                    sys500: '#5B3163',
                    sys600: '#412945',
                },
                systemColor5: {
                    sys100: '#E6E4F1',
                    sys200: '#B4AAE4',
                    sys300Main: '#8962F3',
                    sys400: '#6D48CC',
                    sys500: '#483B6D',
                    sys600: '#342D48',
                },
                systemColor6: {
                    sys100: '#FBE3B1',
                    sys200: '#EFC45E',
                    sys300Main: '#EFB02E',
                    sys400: '#D39822',
                    sys500: '#A06B09',
                    sys600: '#614105',
                },
                neutral: {
                    neu100: '#E8E9EE',
                    neu200: '#BBC2CC',
                    neu300Main: '#8591A2',
                    neu400: '#69778A',
                    neu500: '#4B5A6E',
                    neu600: '#313E4F',
                },
                text: {
                    tex100: '#E9EAEB',
                    tex200: '#BFC2C4',
                    tex300Main: '#8C9194',
                    tex400: '#71777B',
                    tex500: '#535A5F',
                    tex600: '#363E45',
                },
                background: {
                    bacwhite: '#FFFFFF',
                    bacmain: '#F2F4F8',
                    bacopGrey: '#313E4F',
                    bacopWhite: '#FFFFFF',
                },
            },
            isDelete: 0,
            created_at: '2023-01-20T11:54:16.438Z',
            updated_at: '2023-01-20T11:54:16.438Z',
            __v: 0,
        },
    },
};
export const DefaultThemeFonts = {
    project_id: '123',
    font: {
        statusCode: 200,
        message: 'success',
        result: {
            _id: '63ca80e894461ae48cb57495',
            projectId: '63ca80e894461ae48cb57493',
            families: ['poppins'],
            urls: ['https://fonts.googleapis.com/css?family=Poppins'],
            fonts: {
                h1: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '4.25rem',
                    lineHeight: '6rem',
                    lineSpacing: '0rem',
                },
                h2: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '3.5rem',
                    lineHeight: '5rem',
                    lineSpacing: '0rem',
                },
                h3: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '2.75rem',
                    lineHeight: '4rem',
                    lineSpacing: '0rem',
                },
                h4: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '2rem',
                    lineHeight: '3rem',
                    lineSpacing: '0rem',
                },
                h5: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '1.75rem',
                    lineHeight: '2.25rem',
                    lineSpacing: '0rem',
                },
                h6: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '1.5rem',
                    lineHeight: '2rem',
                    lineSpacing: '0rem',
                },
                h7: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '1.25rem',
                    lineHeight: '2rem',
                    lineSpacing: '0rem',
                },
                h8: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '1.125rem',
                    lineHeight: '1.5rem',
                    lineSpacing: '0rem',
                },
                body1: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '1rem',
                    lineHeight: '1.25rem',
                    lineSpacing: '0rem',
                },
                body2: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '0.875rem',
                    lineHeight: '1.25rem',
                    lineSpacing: '0rem',
                },
                underline1: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '1rem',
                    lineHeight: '1.25rem',
                    lineSpacing: '0rem',
                },
                underline2: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '0.875rem',
                    lineHeight: '1.25rem',
                    lineSpacing: '0rem',
                },
                caption: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '0.75rem',
                    lineHeight: '1rem',
                    lineSpacing: '0rem',
                },
                overline: {
                    fontFamily: 'Poppins',
                    fontWeight: '37.5rem',
                    fontSize: '0.6875rem',
                    lineHeight: '0.875rem',
                    lineSpacing: '0rem',
                },
            },
            isDelete: 0,
            created_at: '2023-01-20T11:54:16.437Z',
            updated_at: '2023-01-20T11:54:16.437Z',
            __v: 0,
        },
    },
};
