export interface IThemeColor {
  main?: string;
  light?: string;
  dark?: string;
  c50?: string;
  c100?: string;
  pri100?: string;
  pri200?: string;
  pri300Main?: string;
  pri400?: string;
  pri500?: string;
  pri600?: string;
  sec100?: string;
  sec200?: string;
  sec400?: string;
  sec500?: string;
  sec600?: string;
  sys100?: string;
  sys200?: string;
  sys400?: string;
  sys500?: string;
  sys600?: string;
  neu100?: string;
  neu200?: string;
  neu400?: string;
  neu500?: string;
  neu600?: string;
  tex100?: string;
  tex200?: string;
  tex400?: string;
  tex500?: string;
  tex600?: string;
  bacwhite?: string;
  bacmain?: string;
  bacopGrey?: string;
  bacopWhite?: string;
  sys300Main?: string;
  sec300Main?: string;
  neu300Main?: string;
  tex300Main?: string;
  contrastDefaultColor?: 'light' | 'dark';
}

// export { default as ebonyClay } from './ebonyClay';
// export { default as aquaBlue } from './aquaBlue';
// export { default as purple } from './purple';
// export { default as green } from './green';
// export { default as red } from './red';
// export { default as orange } from './orange';
// export { default as paleRed } from './paleRed';
// export { default as rhino } from './rhino';
