export const IconList = [
    {label: 'accessibility', value: 'accessibility'},
    {
        label: 'accessible_forward_black_24dp',
        value: 'accessible_forward_black_24dp',
    },
    {label: 'accessible', value: 'accessible'},
    {label: 'Accommodation', value: 'Accommodation'},
    {label: 'account_balance_black_24dp', value: 'account_balance_black_24dp'},
    {
        label: 'account_balance_wallet_black_24dp',
        value: 'account_balance_wallet_black_24dp',
    },
    {label: 'account_box_black_24dp', value: 'account_box_black_24dp'},
    {label: 'account_circle_black_24dp', value: 'account_circle_black_24dp'},
    {label: 'add_alert_black_24dp', value: 'add_alert_black_24dp'},
    {label: 'addchart_black_24dp', value: 'addchart_black_24dp'},
    {
        label: 'add_shopping_cart_black_24dp',
        value: 'add_shopping_cart_black_24dp',
    },
    {label: 'add', value: 'add'},
    {label: 'add_task_black_24dp', value: 'add_task_black_24dp'},
    {label: 'add_to_drive_black_24dp', value: 'add_to_drive_black_24dp'},
    {
        label: 'admin_panel_settings_black_24dp',
        value: 'admin_panel_settings_black_24dp',
    },
    {label: 'ads_click_black_24dp', value: 'ads_click_black_24dp'},
    // { label: 'AHRQ', value: 'AHRQ' },
    {label: 'alarm_add_black_24dp', value: 'alarm_add_black_24dp'},
    {label: 'alarm_black_24dp', value: 'alarm_black_24dp'},
    {label: 'alarm_off_black_24dp', value: 'alarm_off_black_24dp'},
    {label: 'alarm_on_black_24dp', value: 'alarm_on_black_24dp'},
    {label: 'all_inbox_black_24dp', value: 'all_inbox_black_24dp'},
    {label: 'all_out_black_24dp', value: 'all_out_black_24dp'},
    {label: 'analytics_black_24dp', value: 'analytics_black_24dp'},
    {label: 'anchor_black_24dp', value: 'anchor_black_24dp'},
    {label: 'android_black_24dp', value: 'android_black_24dp'},
    {label: 'announcement_black_24dp', value: 'announcement_black_24dp'},
    {label: 'api_black_24dp', value: 'api_black_24dp'},
    {label: 'app_blocking_black_24dp', value: 'app_blocking_black_24dp'},
    // { label: 'app-development 1', value: 'app-development 1' },
    // { label: 'Approve', value: 'Approve' },
    {
        label: 'app_settings_alt_black_24dp',
        value: 'app_settings_alt_black_24dp',
    },
    {label: 'apps_outage_black_24dp', value: 'apps_outage_black_24dp'},
    {label: 'app', value: 'app'},
    {label: 'arrow_back', value: 'arrow_back'},
    {
        label: 'arrow_circle_down_black_24dp',
        value: 'arrow_circle_down_black_24dp',
    },
    {
        label: 'arrow_circle_left_black_24dp',
        value: 'arrow_circle_left_black_24dp',
    },
    {
        label: 'arrow_circle_right_black_24dp',
        value: 'arrow_circle_right_black_24dp',
    },
    {label: 'arrow_circle_up_black_24dp', value: 'arrow_circle_up_black_24dp'},
    {label: 'arrow_downward_black_24dp', value: 'arrow_downward_black_24dp'},
    {label: 'arrow_drop_down_black_24dp', value: 'arrow_drop_down_black_24dp'},
    {
        label: 'arrow_drop_down_circle_black_24dp',
        value: 'arrow_drop_down_circle_black_24dp',
    },
    {label: 'arrow_drop_up_black_24dp', value: 'arrow_drop_up_black_24dp'},
    {label: 'arrow_forward_black_24dp', value: 'arrow_forward_black_24dp'},
    {
        label: 'arrow_forward_ios_black_24dp',
        value: 'arrow_forward_ios_black_24dp',
    },
    {label: 'arrow_left_black_24dp', value: 'arrow_left_black_24dp'},
    {label: 'arrow_right_alt_black_24dp', value: 'arrow_right_alt_black_24dp'},
    {label: 'arrow_right_black_24dp', value: 'arrow_right_black_24dp'},
    {label: 'arrow', value: 'arrow'},
    {label: 'arrow_upward_black_24dp', value: 'arrow_upward_black_24dp'},
    {label: 'article_black_24dp', value: 'article_black_24dp'},
    {label: 'aspect_ratio_black_24dp', value: 'aspect_ratio_black_24dp'},
    {label: 'assessment_black_24dp', value: 'assessment_black_24dp'},
    {label: 'assignment_black_24dp', value: 'assignment_black_24dp'},
    {label: 'assignment_ind_black_24dp', value: 'assignment_ind_black_24dp'},
    {label: 'assignment_late_black_24dp', value: 'assignment_late_black_24dp'},
    {
        label: 'assignment_return_black_24dp',
        value: 'assignment_return_black_24dp',
    },
    {
        label: 'assignment_returned_black_24dp',
        value: 'assignment_returned_black_24dp',
    },
    {
        label: 'assignment_turned_in_black_24dp',
        value: 'assignment_turned_in_black_24dp',
    },
    {
        label: 'assistant_direction_black_24dp',
        value: 'assistant_direction_black_24dp',
    },
    {label: 'attach_file', value: 'attach_file'},
    {label: 'autorenew_black_24dp', value: 'autorenew_black_24dp'},
    // { label: 'baby-teeth', value: 'baby-teeth' },
    {label: 'backup_black_24dp', value: 'backup_black_24dp'},
    {label: 'backup_table_black_24dp', value: 'backup_table_black_24dp'},
    {
        label: 'batch_prediction_black_24dp',
        value: 'batch_prediction_black_24dp',
    },
    {label: 'Behavior', value: 'Behavior'},
    {label: 'book_black_24dp', value: 'book_black_24dp'},
    {label: 'bookmark_add_black_24dp', value: 'bookmark_add_black_24dp'},
    {label: 'bookmark_added_black_24dp', value: 'bookmark_added_black_24dp'},
    {label: 'bookmark_black_24dp', value: 'bookmark_black_24dp'},
    // {
    //   label: 'bookmark_border_black_24dp (1) 1',
    //   value: 'bookmark_border_black_24dp (1) 1',
    // },
    {label: 'book_online_black_24dp', value: 'book_online_black_24dp'},
    {label: 'bug_report_black_24dp', value: 'bug_report_black_24dp'},
    {label: 'build_circle_black_24dp', value: 'build_circle_black_24dp'},
    {label: 'cached_black_24dp', value: 'cached_black_24dp'},
    {label: 'calendar_today_black_24dp', value: 'calendar_today_black_24dp'},
    {
        label: 'calendar_view_day_black_24dp',
        value: 'calendar_view_day_black_24dp',
    },
    {
        label: 'calendar_view_month_black_24dp',
        value: 'calendar_view_month_black_24dp',
    },
    {
        label: 'calendar_view_week_black_24dp',
        value: 'calendar_view_week_black_24dp',
    },
    {label: 'camera_enhance_black_24dp', value: 'camera_enhance_black_24dp'},
    {label: 'campaign_black_24dp', value: 'campaign_black_24dp'},
    {label: 'cancel_black_24dp', value: 'cancel_black_24dp'},
    {
        label: 'cancel_schedule_send_black_24dp',
        value: 'cancel_schedule_send_black_24dp',
    },
    // { label: 'capital-risk', value: 'capital-risk' },
    {label: 'card_giftcard_black_24dp', value: 'card_giftcard_black_24dp'},
    // { label: 'Cardiac Heart', value: 'Cardiac Heart' },
    {label: 'card_membership_black_24dp', value: 'card_membership_black_24dp'},
    {label: 'card_travel_black_24dp', value: 'card_travel_black_24dp'},
    {label: 'Care', value: 'Care'},
    // { label: 'CBAHI', value: 'CBAHI' },
    {label: 'CDC', value: 'CDC'},
    {label: 'change_history_black_24dp', value: 'change_history_black_24dp'},
    // { label: 'chat_black_24dp 1', value: 'chat_black_24dp 1' },
    {label: 'check_black_24dp', value: 'check_black_24dp'},
    {label: 'Checkbox List', value: 'Checkbox List'},
    {label: 'Checkbox', value: 'Checkbox'},
    {label: 'check_circle_black_24dp', value: 'check_circle_black_24dp'},
    {label: 'chevron_left_black_24dp', value: 'chevron_left_black_24dp'},
    {label: 'chevron_right_black_24dp', value: 'chevron_right_black_24dp'},
    {label: 'Claims', value: 'Claims'},
    {label: 'class_black_24dp', value: 'class_black_24dp'},
    {label: 'Clinical', value: 'Clinical'},
    {label: 'close_black_24dp', value: 'close_black_24dp'},
    {
        label: 'close_fullscreen_black_24dp',
        value: 'close_fullscreen_black_24dp',
    },
    // { label: 'Cluster', value: 'Cluster' },
    {label: 'code_black_24dp', value: 'code_black_24dp'},
    {label: 'code_off_black_24dp', value: 'code_off_black_24dp'},
    {label: 'Collapse', value: 'Collapse'},
    {label: 'color_fill', value: 'color_fill'},
    {label: 'comment_bank_black_24dp', value: 'comment_bank_black_24dp'},
    {label: 'Communication', value: 'Communication'},
    {label: 'commute_black_24dp', value: 'commute_black_24dp'},
    {label: 'compare_arrows_black_24dp', value: 'compare_arrows_black_24dp'},
    {label: 'Competition', value: 'Competition'},
    {label: 'compress_black_24dp', value: 'compress_black_24dp'},
    {label: 'contactless_black_24dp', value: 'contactless_black_24dp'},
    {label: 'contact_page_black_24dp', value: 'contact_page_black_24dp'},
    {label: 'contact_support_black_24dp', value: 'contact_support_black_24dp'},
    {label: 'copyright_black_24dp', value: 'copyright_black_24dp'},
    {label: 'credit_card_black_24dp', value: 'credit_card_black_24dp'},
    {label: 'credit_card_off_black_24dp', value: 'credit_card_off_black_24dp'},
    {label: 'Credit', value: 'Credit'},
    // { label: 'Critical', value: 'Critical' },
    // { label: 'ct-scan 1', value: 'ct-scan 1' },
    // { label: 'Cultural', value: 'Cultural' },
    {label: 'dangerous_black_24dp', value: 'dangerous_black_24dp'},
    {label: 'dashboard_black_24dp', value: 'dashboard_black_24dp'},
    {
        label: 'dashboard_customize_black_24dp',
        value: 'dashboard_customize_black_24dp',
    },
    {
        label: 'data_exploration_black_24dp',
        value: 'data_exploration_black_24dp',
    },
    {label: 'date_range_black_24dp', value: 'date_range_black_24dp'},
    // { label: 'Date & Time', value: 'Date & Time' },
    {label: 'delete_black_24dp', value: 'delete_black_24dp'},
    // { label: 'dental-care', value: 'dental-care' },
    // { label: 'dermis', value: 'dermis' },
    {label: 'description_black_24dp', value: 'description_black_24dp'},
    {label: 'Devices', value: 'Devices'},
    {label: 'Diagnisis', value: 'Diagnisis'},
    {label: 'DiamondSolid', value: 'DiamondSolid'},
    {
        label: 'disabled_visible_black_24dp',
        value: 'disabled_visible_black_24dp',
    },
    {label: 'dns_black_24dp', value: 'dns_black_24dp'},
    // { label: 'Doctor', value: 'Doctor' },
    // { label: 'domain_black_24dp 1', value: 'domain_black_24dp 1' },
    {label: 'domain', value: 'domain'},
    {label: 'd_rotation', value: 'd_rotation'},
];
